# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    milestone: 5

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "phpunit/phpunit"
        versions: [ "^9.0", "^10.0" ]
      - dependency-name: "symfony/yaml"
      - dependency-name: "typo3/cms-*"
    versioning-strategy: "increase"
    milestone: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    milestone: 5
